FROM node:20-alpine

WORKDIR /app

# Add node binaries to $PATH for libraries
ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV development

# Thin-install app dependencies
COPY package.json package-lock.json ./
# Dependencies will be installed in docker-entrypoint.sh, so after the volume mount
# RUN npm install --silent

# Add app; non-prod files still useful for local dev
COPY . ./

USER node

EXPOSE 3001

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["npm", "run", "dev"]
